### ISSUE TITLE
WinError 126 The specified module could not be found

### ISSUE THREAD

**Issue by patkalie** [ysbecca/py-wsi#18]
Hi. When I try: "import py_wsi" in a script window in the Python IDE I get the following error "WinError 126 The specified module could not be found". 
I have installed the other required packages I think.
According to the intellisense in the IDE the py_wsi is installed since member objects are displayed. What could be the problem with my installation? Do I have to install openslide in addition to openslide-python?
Kind regards
Kai-Inge

>>> import py_wsi
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import py_wsi
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\py_wsi\__init__.py", line 6, in <module>
    from .patch_reader import *
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\py_wsi\patch_reader.py", line 10, in <module>
    from openslide import open_slide
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\openslide\__init__.py", line 29, in <module>
    from openslide import lowlevel
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\openslide\lowlevel.py", line 41, in <module>
    _lib = cdll.LoadLibrary('libopenslide-0.dll')
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

**Comment by ysbecca** [comment]
Hi Kai-Inge, it looks like the error is coming from openslide. I would debug this separately, and make sure that from a Python shell you are able to do `import openslide` without error. As you can see in the Python openslide binding, you must first install OpenSlide, not just a `pip install openslide`.

https://github.com/openslide/openslide-python

**Comment by patkalie** [comment]
Hi ysbecca. Thank you very much! Downloading the openslide files did the trick. :-)
Kind regards,
Kai-Inge
