### ISSUE TITLE
TypeError: 'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by monjoybme** [ysbecca/py-wsi#7]
I am using MAC OS and python 3.7. I am getting below error. Please suggest how can I solve this issue.

Using cached https://files.pythonhosted.org/packages/32/f4/a4f692b8d7791df38874e678e28c60783284ca4a5fe4f083214f45e4ede2/py_wsi-1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/nh/yztkyf6x0jj10r0n4x25gjb00000gn/T/pip-install-2Meh31/py-wsi/setup.py", line 12, in <module>
        with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
    **TypeError: 'encoding' is an invalid keyword argument for this function**
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/nh/yztkyf6x0jj10r0n4x25gjb00000gn/T/pip-install-2Meh31/py-wsi/

**Comment by monjoybme** [comment]
Issue resolved.
